name: base-image

on:
  schedule:
    - cron: "0 0 * * *"


jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: deps
        run: |
          sudo apt update -qq
          sudo apt install singularity-container
      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PAT }}
      - name: refresh-base
        run: |
          tag=$(date +%Y%m%d)
          python build.py --target base --tag $tag
          docker push ghcr.io/gablab/murfi-base:$tag
          docker tag ghcr.io/gablab/murfi-base:$tag ghcr.io/gablab/murfi-base:latest
          docker push ghcr.io/gablab/murfi-base:latest
