name: build-and-test

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: deps
        run: |
          wget -O- http://neuro.debian.net/lists/jammy.us-ca.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
          sudo apt-key adv --recv-keys --keyserver hkps://keyserver.ubuntu.com 0xA5D32F012649A5A9
          sudo apt update -qq
          sudo apt install singularity-container
      - name: build-headless
        run: |
          bash build-singularity.sh MAKE_TARGET=headless
      - name: test
        run: |
          mkdir example_data
          cd example_data
          curl -fsSL https://www.dropbox.com/s/1vvrz2g4tbzoh5c/murfi_example_data.tgz | tar -xz --strip-components 1
          cd ..
          python test/regression/neurofeedback.py
