name: build-and-test

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: deps
        run: |
          sudo apt update -qq
          sudo apt install singularity-container
      - name: build-headless
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
          bash build-singularity.sh MAKE_TARGET=headless
      - name: test
        run: |
          mkdir example_data
          cd example_data
          curl -L -o murfi_example_data.zip 'https://www.dropbox.com/scl/fo/9f7aeawawaj4oplrri7rs/AM-rVITCP6hgVB1LmvrA8ew?rlkey=pwhjiz5h1zj1lw85i7q56jgus&st=8jily8t6&dl=1'
          unzip murfi_example_data.zip
          cd ..
          python test/regression/neurofeedback.py
