name: build-and-test

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: deps
        run: |
          sudo apt update -qq
      - name: singularity install
        uses: singularityhub/install-singularity@main
      - name: build-headless
        run: sh build-singularity.sh MAKE_TARGET=headless
      - name: test
        run: |
          mkdir example_data
          cd example_data
          curl -fsSL https://www.dropbox.com/s/1vvrz2g4tbzoh5c/murfi_example_data.tgz | tar -xz --strip-components 1
          cd ..
          python test/regression/neurofeedback.py
