name: build-and-test

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PAT }}
      - name: deps
        run: |
          sudo apt update -qq
          sudo apt install singularity-container
      - name: build-headless
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
          bash build-singularity.sh MAKE_TARGET=headless
      - name: test
        run: |
          mkdir example_data
          cd example_data
          curl -fsSL https://www.dropbox.com/s/1vvrz2g4tbzoh5c/murfi_example_data.tgz | tar -xz --strip-components 1
          cd ..
          python test/regression/neurofeedback.py
      - name: Login to GitHub Container Registry - delete me
        run: |
          echo ${{ secrets.GHCR_PAT }} | singularity registry login -u ${{ secrets.GHCR_USER }} --password-stdin docker://ghcr.io
      - name: build-release
        run: |
          bash build-singularity.sh
          singularity push bin/murfi.sif oras://ghcr.io/gablab/murfi2:latest
