name: release

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: deps
        run: |
          sudo apt update -qq
          sudo apt install singularity-container
      - name: Login to GitHub Container Registry
        run: |
          echo ${{ secrets.GHCR_PAT }} | singularity registry login -u ${{ secrets.GHCR_USER }} --password-stdin docker://ghcr.io
      - name: release
        run: |
          bash build-singularity.sh
          singularity push bin/murfi.sif oras://ghcr.io/gablab/murfi2:latest
