name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: deps
        run: |
          sudo apt update -qq
          sudo apt install singularity-container
      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PAT }}
      - name: refresh-base
        run: |
          docker build -t ghcr.io/gablab/murfi2-base:latest -f docker/Dockerfile.base .
          docker push ghcr.io/gablab/murfi2-base:latest
      - name: build
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
          bash build-singularity.sh
      - name: test
        run: |
          curl -L -o murfi_example_data.tgz 'https://www.dropbox.com/scl/fi/orklnabmriean1piyzbxi/murfi_example_data_v2.tgz?rlkey=eymtgx7f7ni6l6ctcc7a0buk0&st=64y08rmc&dl=0'
          tar xzvf murfi_example_data.tgz
          python test/regression/neurofeedback.py
      - name: singularity login
        run: |
          echo ${{ secrets.GHCR_PAT }} | singularity registry login -u ${{ secrets.GHCR_USER }} --password-stdin docker://ghcr.io
      - name: release
        run: |
          bash build-singularity.sh
          singularity push bin/murfi.sif oras://ghcr.io/gablab/murfi2-sif:latest
