name: release

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PAT }}
      - name: deps
        run: |
          sudo apt update -qq
          sudo apt install singularity-container
      - name: release
        run: |
          bash build-singularity.sh
          singularity push bin/murfi.sif oras://ghcr.io/gablab/murfi2:latest
