name: release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: deps
        run: |
          sudo apt update -qq
          sudo apt install singularity-container
      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PAT }}
      - name: refresh-base
        run: |
          python build.py --target base --tag ${{ github.ref_name }}
      - name: build
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
          python build.py --target docker --target singularity --tag ${{ github.ref_name }}
      - name: test
        run: |
          curl -L -o murfi_example_data.tgz 'https://www.dropbox.com/scl/fi/orklnabmriean1piyzbxi/murfi_example_data_v2.tgz?rlkey=eymtgx7f7ni6l6ctcc7a0buk0&st=64y08rmc&dl=0'
          tar xzvf murfi_example_data.tgz
          python test/regression/neurofeedback.py
      - name: singularity login
        run: |
          echo ${{ secrets.GHCR_PAT }} | singularity registry login -u ${{ secrets.GHCR_USER }} --password-stdin docker://ghcr.io
      - name: push
        run: |
          docker push ghcr.io/gablab/murfi-base:${{ github.ref_name }}
          docker tag ghcr.io/gablab/murfi-base:${{ github.ref_name }} ghcr.io/gablab/murfi-base:latest
          docker push ghcr.io/gablab/murfi-base:latest
          docker push ghcr.io/gablab/murfi:${{ github.ref_name }}
          docker tag ghcr.io/gablab/murfi:${{ github.ref_name }} ghcr.io/gablab/murfi:latest
          docker push ghcr.io/gablab/murfi:latest
          singularity push bin/murfi.sif oras://ghcr.io/gablab/murfi-sif:${{ github.ref_name }}
          singularity push bin/murfi.sif oras://ghcr.io/gablab/murfi-sif:latest
