name: test

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PAT }}
      - name: deps
        run: |
          sudo apt update -qq
          sudo apt install singularity-container
      - name: build-headless
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
          bash build-singularity.sh MAKE_TARGET=headless
      - name: test
        run: |
          mkdir example_data
          cd example_data
          curl -L -o murfi_example_data.tgz 'https://www.dropbox.com/scl/fi/61krbyoj293qpeaxcs9zl/murfi_example_data.tgz?rlkey=paljzpw3f9pbpirbdu8fcrhdm&st=jm686tif&dl=1'
          tar xzvf murfi_example_data.tgz
          cd ..
          python test/regression/neurofeedback.py
